#!/usr/bin/env node
// Generates docs/recipes/*.md from spec/recipes.json. Run: node scripts/gen_recipes.mjs [--check]
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(join(root, "spec/recipes.json"), "utf8"));
const fill = (s) => s.replace(/\{\{(\w+)\}\}/g, (_, k) => spec.constants[k] ?? `{{${k}}}`);
const section = (r) => `### ${r.target}\n\n\`\`\`${r.lang}\n${fill(r.code)}\n\`\`\`\n\n<sub>Checked: ${r.verified}</sub>\n`;
const banner = "<!-- GENERATED by scripts/gen_recipes.mjs from spec/recipes.json. Do not edit by hand. -->\n\n";

const mcp = `${banner}# Viktor over MCP: one recipe per framework and client

Viktor hosts a stateless Streamable-HTTP MCP server at \`${spec.constants.MCP_URL}\`. Authenticate with a Viktor
API key as \`Authorization: Bearer <key>\` (\`x-api-key\` also works). The tool list depends on the key's scopes;
\`ask_viktor\` needs \`threads:create\`, \`runs:create\` and \`runs:read\`. A personal key needs a linked Slack or
Teams identity. Waits are capped at 300 s server-side: for longer work call \`wait_for_run\` again, or use the
\`delegate_to_viktor\` tool from a Viktor adapter package. Set client read timeouts above 300 s.

Native packages exist for the Vercel AI SDK, LangChain, Pydantic AI, Mastra and the OpenAI Agents SDK; use those
when you want Viktor as a *model* or a typed delegate tool. MCP is the zero-install path everywhere else.

${spec.mcp.map(section).join("\n")}
## Not supported yet

claude.ai / Claude Desktop connectors and ChatGPT connectors require OAuth on the MCP server; Viktor's server
authenticates with API keys today. Claude Desktop works through the stdio bridge above.
`;

const compat = `${banner}# Viktor through an OpenAI-compatible or Anthropic-compatible base URL

Any framework or app with a base-URL setting can use Viktor as a model with no extra package:

| Wire | Base URL | Notes |
|---|---|---|
| OpenAI Chat Completions and Responses | \`${spec.constants.OPENAI_BASE}\` | model id \`viktor\` |
| Anthropic Messages | \`${spec.constants.ANTHROPIC_BASE}\` | clients append \`/v1/messages\`; model id \`viktor\` |

Rules that apply to every recipe: use a long timeout (a Viktor turn can run for up to 600 s while it works in its
own tools), turn automatic retries off (a failed Viktor run was billed and may have acted), pass tool-call ids back
unchanged (they are routing tokens), and expect system prompts to be added to Viktor's own instructions.
These recipes do not add Viktor's typed errors or empty-reply detection; the native adapter packages do.

${spec.openai_compatible.map(section).join("\n")}`;

const outputs = { "docs/recipes/mcp.md": mcp, "docs/recipes/openai-compatible.md": compat };
let stale = false;
for (const [path, content] of Object.entries(outputs)) {
  const abs = join(root, path);
  if (process.argv.includes("--check")) {
    if (!existsSync(abs) || readFileSync(abs, "utf8") !== content) { console.error(`stale: ${path}`); stale = true; }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
}
if (stale) process.exit(1);
console.log(process.argv.includes("--check") ? "recipes up to date" : `generated ${Object.keys(outputs).length} files (${spec.mcp.length} MCP, ${spec.openai_compatible.length} compat recipes)`);
