#!/usr/bin/env node
// Generates language-specific copies of spec/*.json so packages stay self-contained.
// TS: packages/core/src/generated/spec.ts   Py: python/core/src/viktor_integrations_core/_spec.py
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tool = JSON.parse(readFileSync(join(root, "spec/delegate-tool.json"), "utf8"));
const errors = JSON.parse(readFileSync(join(root, "spec/errors.json"), "utf8"));
const banner = "GENERATED by scripts/sync_spec.mjs from spec/*.json. Do not edit.";

const ts = `// ${banner}
export const DELEGATE_TOOL_SPEC = ${JSON.stringify(tool, null, 2)} as const;
export const ERROR_SPEC = ${JSON.stringify(errors, null, 2)} as const;
`;
const tsOut = join(root, "packages/core/src/generated/spec.ts");
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(tsOut, ts);

const pyDir = join(root, "python/core/src/viktor_integrations_core");
if (existsSync(pyDir)) {
  const py = `# ${banner}
import json

DELEGATE_TOOL_SPEC = json.loads(r'''${JSON.stringify(tool)}''')
ERROR_SPEC = json.loads(r'''${JSON.stringify(errors)}''')
`;
  writeFileSync(join(pyDir, "_spec.py"), py);
}
console.log("spec synced");
